### ISSUE TITLE
Doxygen

### ISSUE THREAD

**Issue by ds5678** [btzy/nativefiledialog-extended#119]
After #118 is merged, I want to convert the existing comments to [Doxygen](https://www.doxygen.nl/manual/docblocks.html) syntax. That will enable other parsers (such as CppSharp) to pick up the documentation and use it in their own code generation. Is that ok with you?

**Comment by btzy** [comment]
I'm happy to accept a PR for this.  The current comment syntax was mostly inherited from https://github.com/mlabbe/nativefiledialog and I agree it is kinda unusual.

**Comment by ds5678** [comment]
Can the max character count be increased? That would make it easier for me to format lines correctly.

**Comment by ds5678** [comment]
It is currently set to 100. 125 would be sufficient to format the lines.

**Comment by btzy** [comment]
Hmm, I was under the impression that Doxygen will only generate a line/paragraph break if you leave at least one blank line in code.

For example:
```
/**
 * Blah1
 * Blah2
 */
```
... generates

> Blah1 Blah2

and
```
/**
 * Blah1
 *
 * Blah2
 */
```
... generates

> Blah1
>
> Blah2

**Comment by btzy** [comment]
Evidence on the internet concurs with me: https://stackoverflow.com/questions/20508669/how-to-set-multiple-lines-in-a-doxygen-paragraph

There might be some flag you can set on the CppSharp documentation parser to make it behave like Doxygen.
