### ISSUE TITLE
CI bug?

### ISSUE THREAD

**Issue by ds5678** [btzy/nativefiledialog-extended#124]
I've been working on generating automated builds for use in NuGet packages, and I noticed something in your build script:

https://github.com/btzy/nativefiledialog-extended/blob/b73cf4cdfc644deda95ceffb355a84b28a34bb88/.github/workflows/cmake.yml#L52

This appears to be a bug because it doesn't match the other ones in the file.

https://github.com/btzy/nativefiledialog-extended/blob/b73cf4cdfc644deda95ceffb355a84b28a34bb88/.github/workflows/cmake.yml#L46

https://github.com/btzy/nativefiledialog-extended/blob/b73cf4cdfc644deda95ceffb355a84b28a34bb88/.github/workflows/cmake.yml#L33

**Comment by btzy** [comment]
Thanks for the catch!  Yes, this is definitely a bug.

**Comment by btzy** [comment]
Fixed by https://github.com/btzy/nativefiledialog-extended/commit/397c4ba9f41683d454e33a5888f1a5db5ff3af67.
