### ISSUE TITLE
Standalone Library build instructions always build Debug version

### ISSUE THREAD

**Issue by atoone** [btzy/nativefiledialog-extended#130]
Following the instructions for building the standalone library, and running:

`cmake -DCMAKE_BUILD_TYPE=Release ..`
`cmake --build .`

in a build subdirectory produces a Debug build, not a release build? 

System: Windows 11, running cmake 3.29 and compiler MSVC/Visual Studio 19.

**Comment by btzy** [comment]
It turns out that MSVC is different, and you should do run these commands instead of the two commands you mentioned:
```
cmake ..
cmake --build . --config Release
```
