### ISSUE TITLE
Not able to import file with non-ASCII characters in the path on Windows

### ISSUE THREAD

**Issue by MeGaL0DoN** [btzy/nativefiledialog-extended#133]
The description claims that "Native character set (UTF-16 wchar_t) support on Windows". However, I was not able to get it working. I tried using NFD::UniquePathU8 instead of NFD::UniquePath, but that doesn't seem to work, as there is no way to cast it to wchar_t*, it can be casted only to char*, like the NFD::UniquePath.

**Comment by MeGaL0DoN** [comment]
Sorry, I found that I am supposed to use NFD::UniquePathN instead.

**Comment by MeGaL0DoN** [comment]
I know that U8 stands for UTF-8, but for what does N stand in UniquePathN?

**Comment by btzy** [comment]
`N` stands for "native".
