### ISSUE TITLE
[OSX] Dialog does not capture focus

### ISSUE THREAD

**Issue by PolyMeilex** [btzy/nativefiledialog-extended#14]
- OS: OSX 19.6.0

I have opened a similar issue in the original nfd repo, but I had no luck finding help there, but this fork looks a lot more maintained so I decided to ask here, so...

My file dialogs on MacOs do not catch the focus no matter how hard I try, which also means that the keyboard does not work and only some mouse inputs reach the dialog.

The described problem is present in `nativefiledialog`, `nativefiledialog-extended`, and in `osdialog`, but it does not occur when using `osascript`

### GIF:
_Top one is `nfd` dialog, bottom one is `osascript` dialog for comparasion_
![GIF](https://i.imgur.com/orDuaYR.gif)

### Workaround that I found that can potentially help to narrow down the problem:
- Open some sort of window/prompt/dialog (I used `NSAlert`)
- After the `NSAlert` is closed open `NSOpenPanel` (closing is not necessary)
- Done, now file dialog will work as expected 

### Another Workaround that I found
- I have to click on the very edge of dialog, and then it catches focus and works as expected:
![GIF](https://i.imgur.com/LwC40Dd.gif)

**Comment by btzy** [comment]
Does this StackOverflow answer solve your problem?  https://stackoverflow.com/questions/60170678/swift-mac-os-application-nssavepanel-does-not-behave-correctly-with-a-backgro

**Comment by PolyMeilex** [comment]
Looks very promising, thank you very much, I'll look into that

**Comment by PolyMeilex** [comment]
Yep, I implemented it quickly and it works as expected, Thank you very much.

**Comment by btzy** [comment]
Could you help me check if this PR branch works as expected (without using the StackOverflow answer)?  I implemented a fix to automatically set the activation policy if needed.  https://github.com/btzy/nativefiledialog-extended/pull/16

**Comment by PolyMeilex** [comment]
Sure thing, binaries from `/test` folder all work as expected. I haven't tested it with `SDL2` (or in my case with `winit`) but judging by your implementation those use case will stay unaffected.
