### ISSUE TITLE
How to use NFD on Win64? Dll Error when appl started.

### ISSUE THREAD

**Issue by sevstels** [btzy/nativefiledialog-extended#142]
![dll-err](https://github.com/btzy/nativefiledialog-extended/assets/13213368/f342a780-10cd-482d-9dac-e45e7d8e403c)

An error appears when launching the 64bit Release application: 
Entry point to procedure cocreateinstance not found in the dll
For 64bit Debug version it vorking well.

How do fix the problem?
Thanks

**Comment by btzy** [comment]
This issue as described is not reproduceable as it works on my machine, and so I think it is likely an issue with your setup.  Perhaps try downloading the binaries from GitHub Actions and running them on your machine?  I think the "Windows latest - MSVC, Static" build uses x64 Release.

**Comment by btzy** [comment]
Closing as not reproduceable.  I suspect a corrupt build process or some OS system files are missing.  It may be reopened if further information is provided.
