### ISSUE TITLE
how to select  a mixture of files and folders 

### ISSUE THREAD

**Issue by lsq** [btzy/nativefiledialog-extended#146]
I want to have a single class using it I can select a file or a folder or some files or some folders or a mixture of them. I searched for such a utility but found nothing.

**Comment by btzy** [comment]
This is not supported by NFDe, and I do not think this is implementable in any platform except macOS.  On Windows, Linux/GTK, and Linux/Portal, there is a boolean flag that is toggled to select either folders or files, and so there is no way to specify that we want to select both.
