### ISSUE TITLE
can help me create a wrapper version for c#?

### ISSUE THREAD

**Issue by unominhtuan** [btzy/nativefiledialog-extended#18]
I am working with AvaloniaUI, sorry, Avalonia OpenFileDialog is not suitable for NativeAOT compiler. Can you help me create the wrapper version for .net of this library?
Thanks very much

**Comment by btzy** [comment]
Sorry, I'm not familiar with .NET native bindings.  But if you attempt to create an optional .NET wrapper for this, I'd be happy to receive a PR.
