### ISSUE TITLE
C++ PickFolder, pass UniquePath by reference

### ISSUE THREAD

**Issue by epezent** [btzy/nativefiledialog-extended#2]
In the C++ version, the PickFolder functions do not pass UniquePathN and UniquePathU8 by reference as the other functions do. This results in a compiler error:

error C2280: 'std::unique_ptr<nfdchar_t,NFD::PathDeleter<nfdchar_t>>::unique_ptr(const std::unique_ptr<nfdchar_t,NFD::PathDeleter<nfdchar_t>> &)': attempting to reference a deleted function

https://github.com/btzy/nativefiledialog-extended/blob/916a0af489144c0a8c8c03a8072cea61ca7fe6f5/src/include/nfd.hpp#L196

https://github.com/btzy/nativefiledialog-extended/blob/916a0af489144c0a8c8c03a8072cea61ca7fe6f5/src/include/nfd.hpp#L233

Changing these to references resolved the issue for me.

**Comment by btzy** [comment]
Thanks for reporting the issue!

I've pushed a fix for this, and also added a test for the C++ interface for PickFolder.
