### ISSUE TITLE
undefined reference to *gtk something*

### ISSUE THREAD

**Issue by GreedyTactician** [btzy/nativefiledialog-extended#59]
Can't build the project. Getting undefined reference. 

Tried to fix it by half haphazardly throwing the following cmake code I found online but it didn't work:
FIND_PACKAGE ( PkgConfig REQUIRED )
PKG_CHECK_MODULES( GTK REQUIRED gtk+-3.0 ) 
INCLUDE_DIRECTORIES ( ${GTK_INCLUDE_DIRS} )
include_directories(${GTK3_INCLUDE_DIRS})
link_directories(${GTK3_LIBRARY_DIRS})
add_definitions(${GTK3_CFLAGS_OTHER})
...
target_link_libraries(app PUBLIC ${GTK3_LIBRARIES})

libgtk-3-dev is installed an up to date.

**Comment by btzy** [comment]
It might help to take a look the CMakeLists file in the test folder, as well as how [other projects](https://github.com/btzy/nativefiledialog-extended/wiki/Native-File-Dialog-Extended-in-the-wild) import NFDe.  The information you have provided is too vague to give any definite answer.

**Comment by GreedyTactician** [comment]
Thank you
