### ISSUE TITLE
Add versioning/tags

### ISSUE THREAD

**Issue by jonathanspw** [btzy/nativefiledialog-extended#74]
Can you add versioning/tags so this can be included in OS repositories?  I'm planning to package it for Fedora/EPEL as a dependency of something else.

**Comment by btzy** [comment]
Sure, that's definitely doable.  Would the typical annotated git tags suffice, e.g. `git tag -a v1.0.0`?

**Comment by jonathanspw** [comment]
Yep that would be perfect!

**Comment by btzy** [comment]
Thanks!  Done, pushed tag "v1.0.0".
