### ISSUE TITLE
WIN: "Error creating ShellItem" when defaultPath uses forward slashes instead of backward slashes

### ISSUE THREAD

**Issue by API-Beast** [btzy/nativefiledialog-extended#8]
NFD_SaveDialogU8 fails on Windows if the passed defaultPath contains forward slashes "/" instead of backward slashes "\".

NFD_GetError() returns "Error creating ShellItem".

**Comment by btzy** [comment]
Thanks for reporting the issue!  This seems to be an issue for all the dialogs on Windows - not only the SaveDialog.

I think we should probably normalize the defaultPath for the U8 versions of the APIs, but perhaps not for the native versions.  Users of the native versions are expected to already be using special code for Windows (or are only using NFD for Windows development only), and so they should already be using backslashes.
