### ISSUE TITLE
Tag a new version?

### ISSUE THREAD

**Issue by Sil3ntStorm** [btzy/nativefiledialog-extended#80]
Could you tag a new version with the latest changes on master?

**Comment by btzy** [comment]
Sure, I can do that. Pardon my lack of experience with versioning, but would bumping just the patch version be appropriate here, where the only thing that changed is the CMakeLists file?

**Comment by Sil3ntStorm** [comment]
According to the commits support for building a shared version was included, which might be nice for some.
And yes simply calling it 1.0.1 would be fine.

**Comment by btzy** [comment]
Released v1.0.1: https://github.com/btzy/nativefiledialog-extended/releases/tag/v1.0.1
