### ISSUE TITLE
NFD_ClearError() for MacOS

### ISSUE THREAD

**Issue by iTrooz** [btzy/nativefiledialog-extended#87]
Hi !

NFD_ClearError() is not defined in `nfd_cocoa.m`, which make calls to `NFD::ClearError()` fail when compiling on MacOS

Is this normal behavior ?

Linked: https://github.com/WerWolv/ImHex/pull/995

**Comment by btzy** [comment]
Thanks!  That's a bug, it seems that I forgot to write that function.
