### ISSUE TITLE
PickFolder returns a file path on Ubuntu 20.04

### ISSUE THREAD

**Issue by krupkat** [btzy/nativefiledialog-extended#91]
Hello and thanks for the great library!

I have an issue when calling PickFolder with the portal implementation, it shows up on Ubuntu 20.04, nfde 1.0.2, running the included test.

Build config: `cmake -DCMAKE_BUILD_TYPE=Release -DNFD_PORTAL=ON ..`, this is the result:

```bash
~/nativefiledialog-extended/build$ ./test/test_pickfolder_c
Success!
/home/tom/xpano/tests/data/image00.jpg
```
The picker is correctly titled "Select Folder", but the individual files are not greyed out and the returned value is the full path to the first file. I haven't figured out a way to select just the directory path.

![20](https://user-images.githubusercontent.com/6817216/230715036-1c915209-f195-4047-82b4-fe3c49999aee.png)

latest available libdbus version is installed:
```
libdbus-1-dev/focal-updates,focal-security,now 1.12.16-2ubuntu2.3 amd64 [installed]
```

With the GTK implementation the files are greyed out as expected and a directory path is returned:

![image](https://user-images.githubusercontent.com/6817216/230715207-b260fc28-b3dc-4069-bfa8-5b7db5d305fb.png)

```
~/nativefiledialog-extended/build$ ./test/test_pickfolder_c
Success!
/home/tom/xpano/tests/data
```

Also with Ubuntu 22.04 the library works as expected both in portal and GTK implementations.

**Comment by btzy** [comment]
I suspect that the version of xdg-desktop-portal installed on your Ubuntu 20.04 machine is old.  Can you check what version you have installed (I think you will need to check both `xdg-desktop-portal` and `xdg-desktop-portal-gtk`)?

The portal implementation uses the [org.freedesktop.portal.FileChooser](https://flatpak.github.io/xdg-desktop-portal/#gdbus-org.freedesktop.portal.FileChooser) API, and NFD_PickFolder sets the `directory` option, which according to that link was added in version 3 of xdg-desktop-portal.  If you are using something prior to version 3, the `directory` option will be ignored, and so the file chooser will only select files.

There isn't a way to resolve this from the point of view of NFDe, but perhaps NFD_PickFolder could be made to check the xdg-desktop-portal version dynamically, and return an error if it is less than 3.

**Comment by krupkat** [comment]
I see, thanks.

These are the versions I have:
```
xdg-desktop-portal-gtk/focal-updates,now 1.6.0-1ubuntu1 amd64 [installed,automatic]
xdg-desktop-portal/focal-updates,now 1.6.0-1ubuntu2 amd64 [installed,automatic]
```
I figured out that the "version 3" in the docs corresponds to an internal versioning scheme for the interface:
https://github.com/flatpak/xdg-desktop-portal/commit/00b28db5ca45bcbdfea0ddfff8447a3f8836bfd9

I didn't find out yet, which release this is in.

I think it would be nice to get an error from NFDe in the < 3 case.

**Comment by btzy** [comment]
Thanks for checking!  I agree that NFDe should probably check the version at runtime and return NFD_ERROR if it is less than 3 for NFD_PickFolder.  Opening a file picker when it can't open a folder picker isn't a "fallback" - it will not be usable.

**Comment by btzy** [comment]
I tested this on Ubuntu 22.04 (interface version 3), and noticed that the portal file picker will allow me to select folders, even if the `directory` flag is not set.

If the Ubuntu 20.04 file picker selects both files and folders too, then adding the interface version check would make it impossible to select a folder when previously the user would just need to be careful to select a folder instead of a file.  Isn't it then worse to add the version check?

**Comment by krupkat** [comment]
Thanks a lot for looking into this. I'll recheck later today, but I'm my experience it wasn't possible to select just a folder in 20.04.

**Comment by btzy** [comment]
Thanks!  I set up an Ubuntu 20.04 VM to verify it, and indeed neither `test_opendialog_c` and `test_opendialogmultiple_c` will select a directory.

**Comment by btzy** [comment]
I have also tested it with the GTK backend on both Ubuntu 20.04 and 22.04; neither `test_opendialog_c` nor `test_opendialogmultiple_c` will select a directory.

**Comment by krupkat** [comment]
Thanks a lot! :)
